# Generated by Django 5.2.3 on 2025-06-12 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    Member = apps.get_model('gym', 'Member')
    for row in Member.objects.all():
        row.uuid = str(uuid.uuid4())
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Inserire un numero di telefono valido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('subscription_start', models.DateField(verbose_name='Data inizio abbonamento')),
                ('subscription_end', models.DateField(verbose_name='Data fine abbonamento')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membri',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='Check-in')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Check-out')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.member', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Accesso',
                'verbose_name_plural': 'Accessi',
                'ordering': ['-check_in'],
            },
        ),
        migrations.RunPython(gen_uuid),
    ]
