# Generated by Django 5.2.3 on 2025-06-12 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='member',
            name='uuid',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
