# Generated by Django 5.2.3 on 2025-06-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_member_id_alter_member_phone_alter_member_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payment_type',
            field=models.CharField(choices=[('carta', 'Carta'), ('contanti', 'Contanti')], default='carta', max_length=10, verbose_name='Tipo di Pagamento'),
        ),
        migrations.AddField(
            model_name='member',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero Ricevuta'),
        ),
    ]
