# Generated by Django 5.2.3 on 2025-06-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_member_payment_type_member_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinout',
            name='subscription_status',
            field=models.CharField(choices=[('attivo', 'Attivo'), ('scaduto', 'Scaduto')], default='attivo', max_length=10, verbose_name='Stato Abbonamento al Check-in'),
        ),
    ]
