# Generated by Django 5.2.3 on 2025-08-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_checkinout_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='medical_certificate_end',
            field=models.DateField(blank=True, null=True, verbose_name='Data fine certificato medico'),
        ),
        migrations.AddField(
            model_name='member',
            name='medical_certificate_start',
            field=models.DateField(blank=True, null=True, verbose_name='Data inizio certificato medico'),
        ),
    ]
