# Generated by Django 5.2.3 on 2025-08-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_member_medical_certificate_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='Foto del membro'),
        ),
    ]
