# Generated by Django 5.2.3 on 2025-09-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='registration_fee_paid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Iscrizione pagata fino al'),
        ),
    ]
