# Generated by Django 5.2.3 on 2025-09-10 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(editable=False, max_length=36, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('subscription_start', models.DateField(verbose_name='Data inizio abbonamento')),
                ('subscription_end', models.DateField(verbose_name='Data fine abbonamento')),
                ('medical_certificate_start', models.DateField(blank=True, null=True, verbose_name='Data inizio certificato medico')),
                ('medical_certificate_end', models.DateField(blank=True, null=True, verbose_name='Data fine certificato medico')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sala_member_photos/', verbose_name='Foto del membro')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='sala_qr_codes/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(choices=[('carta', 'Carta'), ('contanti', 'Contanti')], default='carta', max_length=10, verbose_name='Tipo di Pagamento')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='Numero Ricevuta')),
                ('registration_fee_paid_until', models.DateField(blank=True, null=True, verbose_name='Iscrizione pagata fino al')),
            ],
            options={
                'verbose_name': 'Membro Sala',
                'verbose_name_plural': 'Membri Sala',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Membro', 'verbose_name_plural': 'Membri'},
        ),
    ]
