# Generated by Django 5.2.3 on 2025-09-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_salamember_alter_member_options'),
    ]

    operations = [
    ]
