# Generated by Django 5.2.3 on 2025-09-10 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_auto_20250910_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaCheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='Check-in')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Check-out')),
                ('subscription_status', models.CharField(choices=[('attivo', 'Attivo'), ('scaduto', 'Scaduto')], default='attivo', max_length=10, verbose_name='Stato Abbonamento al Check-in')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.salamember', verbose_name='Membro Sala')),
            ],
            options={
                'verbose_name': 'Accesso Sala',
                'verbose_name_plural': 'Accessi Sala',
                'ordering': ['-check_in'],
            },
        ),
    ]
