# Generated by Django 5.2.3 on 2026-05-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_salacheckinout'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Nota'),
        ),
        migrations.AddField(
            model_name='salamember',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Nota'),
        ),
    ]
