# Generated by Django 5.2.3 on 2026-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_member_note_salamember_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='salamember',
            name='course_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tipo di corso'),
        ),
    ]
