# Generated by Django 5.2.3 on 2026-05-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_salamember_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='subscription_status',
            field=models.CharField(choices=[('attivo', 'Attivo'), ('scaduto', 'Scaduto')], default='attivo', max_length=64, verbose_name='Stato Abbonamento al Check-in'),
        ),
        migrations.AlterField(
            model_name='member',
            name='payment_type',
            field=models.CharField(choices=[('carta', 'Carta'), ('contanti', 'Contanti')], default='carta', max_length=64, verbose_name='Tipo di Pagamento'),
        ),
        migrations.AlterField(
            model_name='salacheckinout',
            name='subscription_status',
            field=models.CharField(choices=[('attivo', 'Attivo'), ('scaduto', 'Scaduto')], default='attivo', max_length=64, verbose_name='Stato Abbonamento al Check-in'),
        ),
        migrations.AlterField(
            model_name='salamember',
            name='payment_type',
            field=models.CharField(choices=[('carta', 'Carta'), ('contanti', 'Contanti')], default='carta', max_length=64, verbose_name='Tipo di Pagamento'),
        ),
    ]
